"""empty message

Revision ID: dd94da5b9823
Revises: 1509a69b03dd
Create Date: 2020-12-20 00:23:54.859592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd94da5b9823'
down_revision = '1509a69b03dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_lists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=0)
    op.alter_column('todos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=0)
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('todo_lists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
