"""empty message

Revision ID: ebc710f31b2c
Revises: b65cd8af324b
Create Date: 2020-12-19 00:51:35.469033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc710f31b2c'
down_revision = 'b65cd8af324b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    op.alter_column('todos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
